MacForYou/MacForYou/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.shortcuts import render
from django.conf.urls.static import static
from django.conf import settings


from beereview.views import  beer_type, index_view, user_review_list

# def root(request):
#     return render(request, 'root.html')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    # url(r'^beer/full_list/$', BeerListView.as_view()),
    # url(r'^beer/(?P<slug>[\w-]+)/$', BeerDetailView.as_view()),
    url(r'^beertype/(?P<slug>[\w-]+)/$', beer_type, name='beer_type'),
    url(r'^user/(?P<pk>\d+)/$', user_review_list, name='user_review_list'),
    url(r'^beers/', include('beereview.urls', namespace='beers')),
    url(r'^community/', include('community.urls', namespace='community')),
    url(r'^$', index_view, name='index'),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MacForYou/beereview/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [


    url(r'^$', views.beers_list, name='beers_list'),

    # url(r'^type/(?P<slug>[\w-]+)', views.beer_type, name='beer_type'),

    url(r'^search/(?P<slug>[\w-]+)', views.beer_search, name='beer_search'),

    url(r'^(?P<slug>[\w-]+)/create/', views.review_create, name='review_create'),

    # url(r'^(?P<pk>\d+)/edit', views.review_edit, name='review_edit'),
    # url(r'^(?P<pk>\d+)/del', views.review_delete,name='review_delete'),
    url(r'^(?P<slug>[\w-]+)/del/', views.review_delete,name='review_delete'),
    url(r'^(?P<slug>[\w-]+)/', views.beer_detail, name='beer_detail'),




#     url(r'^(?P<pk>\d+)/', views.review_detail, name='review_detail'),
    # url(r'^$', views.full_list, name='full_list'),
    # url(r'^(?P<slug>[\w-]+)/$', views.beer_detail, name='beer_detail'),
 	#url(r'^create/$', views.review_create, name='review_create'),
 	#url(r'^(?P<slug>[\w-]+)/detail', views.beer_detail, name='beer_detail'),
	# url(r'^(?P<slug>[\w-]+)/type', views.beer_type, name='beer_type'),
    # url(r'^(?P<pk>\d+)/edit', views.review_edit, name='review_edit'),
    # url(r'^(?P<pk>\d+)/del', views.review_delete,name='review_delete'),
    # url(r'^(?P<pk>\d+)/', views.review_detail, name='review_detail'),

]

MacForYou/community/urls.py
from django.conf.urls import url
from . import views

app_name = 'community'
urlpatterns = [
	url(r'^$', views.meetup_view, name='meetups'),
	url(r'^(?P<meetup_id>[0-9]+)/$', views.meetup_detail, name='meetup_detail'),
	#url(r'^(?P<party_id>[0-9]+)/results/$', views.results, name='results'),
	url(r'^(?P<party_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'^(?P<meetup_id>[0-9]+)/edit/$', views.meetup_edit, name='meetup_edit'),
	url(r'^create$', views.meetup_create, name='meetup_create'),
	#url(r'^choice_create$', views.choice_create, name='choice_create'),
	url(r'^(?P<pk>\d+)/likes/$', views.party_likes, name='meetup_likes'), 

]

MacForYou/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>MacForYou</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.css">
	<style type="text/css">
		body {
			background-color: #FFFFFF;
			/*background-color: #F2F3F5;*/
		}
		.Site{
			display: flex;
			min-height: 100vh;
			flex-direction: column;
		}

		.ui.main.container{
			flex: 1 0 auto;
		}

		.ui.menu .item img.logo {
		    margin-right: 1em;
		}

	  	.ui.fluid.icon.input.beer.search {
			width: 200px;
	  	}
		.footer.segment {
    		padding: 2em 0em;
    	}

    	.ui.kakao.button {
    		background-color: #ffeb00;
    		color: rgba(0,0,0,0.53);
    	}

	  @media only screen and (max-width: 767px){
	  	.ui.fluid.icon.input.beer.search {
			width: 150px;
		}
		.ui.item.navlogin{
			padding-left: 0px;
		}
		.ui.item.navlogout{
			padding-left: 0px;
		}
		.header.item.nav{
			padding-left: 7px;
		}
		.footer.segment {
    		padding: 1em 0em;
    		flex: none;
    	}

/*    	.footer.segment > .ui.container > .ui.stackable.divided.equal.grid > .three.wide.column{
    		padding-top: 1em;
    		padding-bottom: 1em;
    	}
    	.footer.segment > .ui.container > .ui.stackable.divided.equal.grid > .seven.wide.column{
    		padding-top: 1em;
    		padding-bottom: 1em;
    	}
*/
	  }		
	</style>
	{% block custom_css_for_page %}
	{% endblock custom_css_for_page %}
</head>
<body class="Site">
	{% block nav %}
		{% include "nav.html" %}
	{% endblock nav %}

	{% block content %} 
	{% endblock content %}

	{% block footer %}
	{% endblock footer %}

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>		
	<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.js"></script>

	<!--- under this needs to go to bottom line -->
	<script type="text/javascript">
	  $(".search.link.icon.nav").click(function(){
	  	var search_text = $("#beer_search").val();
	  	var full_search_url = '/beers/search/' + search_text;
	  	window.location.href=full_search_url;
	  });
	  $("#beer_search").keypress(function(e){
	  	if (e.which == 13){
	  		$(".search.link.icon.nav").click();
	  		return false;
	  	}
	  });

	</script>
	{% block custom_script %}
	{% endblock custom_script %}
	
</body>
</html>

MacForYou/templates/footer.html
<div class="ui inverted vertical footer segment">
  <div class="ui container">
    <div class="ui stackable inverted stackable grid">
      <div class="three wide column">
        <h4 class="ui inverted header">About</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">About Us</a>
          <a href="#" class="item">Contact Us</a>
          <!-- <a href="#" class="item">Religious Ceremonies</a>
          <a href="#" class="item">Gazebo Plans</a> -->
        </div>
      </div>
<!--       <div class="three wide column">
        <h4 class="ui inverted header">Services</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Banana Pre-Order</a>
          <a href="#" class="item">DNA FAQ</a>
          <a href="#" class="item">How To Access</a>
          <a href="#" class="item">Favorite X-Men</a>
        </div>
      </div> -->
      <div class="seven wide column">
        <h4 class="ui inverted header">Footer Header</h4>
        <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
      </div>
    </div>
  </div>
</div>

MacForYou/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load socialaccount %}

{% block custom_css_for_page %}
  <style type="text/css">
    .masthead.segment {
      min-height: 420px;
      padding: 1em 0em;          
    }
    .ui.vertical.masthead.center.aligned.segment{
      background-image: url("{% static 'MacForYou_Main_Img.jpg' %}");
    }
    .masthead h1.ui.header {
      margin-top: 2em;
      margin-bottom: 0em;
      font-size: 3em;
      font-weight: normal;
    }
    .pusher {
      margin-top: 52px;
      flex: 1 0 auto;
    }

    @media only screen and (max-width: 700px) {
/*      .ui.fixed.menu {
        display: none !important;
      }
      .secondary.pointing.menu .item,
      .secondary.pointing.menu .menu {
        display: none;
      }
      .secondary.pointing.menu .toc.item {
        display: block;
      }*/
      .masthead.segment {
        min-height: 400px;
      }
      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }
      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
        margin-bottom: 3em;
      }
    }

  </style>
{% endblock custom_css_for_page %}

{% block nav %}
    {% include "nav.html" %}
{% endblock %}

{% block content %}
<div class="pusher">
  <div class="ui vertical masthead center aligned segment">
    <div class="ui text container">
      <h1 class="ui header">
        Imagine-a-Beer
      </h1>
      <h2>That fits YOU Just Right</h2>
      <div class="ui huge primary button">Get Started <i class="right arrow icon"></i></div>
    </div>
  </div>
  <div class="ui vertical stripe segment" style="padding-top: 30px; padding-bottom: 30px;">
    <div class="ui middle aligned stackable grid container">
      <div class="row">
        <div class="center aligned column">
          <h2 class="ui header">Recent Reviews</h2>
        </div>
      </div>
      <div class="row">
        <div class="column">
          <div class="ui four stackable cards">
            {% for recents_review in recents_reviews %}
            <div class="ui card">
              <div class="content">
                <div class="right floated meta">{{ recents_review.beereview.created|timesince }}</div>
                {% get_social_accounts recents_review.review_user as accounts %}                
                <img class="ui avatar image" src="{{accounts.kakao.0.get_avatar_url}}"> {{ recents_review.review_user_profile.nickname}}
              </div>
              <a class="image" href="{% url 'beers:beer_detail' recents_review.review_beer.name %} ">
                <img src="{{ recents_review.review_beer.beer_image.main.url }}">
              </a>
              <div class="content">
                  {{ recents_review.beereview.comment|truncatechars:35 }}
              </div>
            </div>
            {% endfor %}
          </div>
        </div>        
      </div>
<!--       <div class="row">
        <div class="ui three stackable cards">
          <div class="card">
            <div class="image">
              <img src="/images/avatar/large/veronika.jpg">
            </div>
          </div>
          <div class="card">
            <div class="image">
              <img src="/images/avatar/large/stevie.jpg">
            </div>
          </div>
          <div class="card">
            <div class="image">
              <img src="/images/avatar/large/steve.jpg">
            </div>
          </div>
        </div>
      </div> -->
    </div>
  </div>


<!--   <div class="ui vertical stripe segment">
    <div class="ui middle aligned stackable grid container">
      <div class="row">
        <div class="eight wide column">
          <h3 class="ui header">We Help Companies and Companions</h3>
          <p>We can give your company superpowers to do things that they never thought possible. Let us delight your customers and empower your needs...through pure data analytics.</p>
          <h3 class="ui header">We Make Bananas That Can Dance</h3>
          <p>Yes that's right, you thought it was the stuff of dreams, but even bananas can be bioengineered.</p>
        </div>
        <div class="six wide right floated column">
          <img src="assets/images/wireframe/white-image.png" class="ui large bordered rounded image">
        </div>
      </div>
      <div class="row">
        <div class="center aligned column">
          <a class="ui huge button">Check Them Out</a>
        </div>
      </div>
    </div>
  </div> -->
  
<!--   <div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled grid">
      <div class="center aligned row">
        <div class="column">
          <h3>"What a Company"</h3>
          <p>That is what they all say about us</p>
        </div>
        <div class="column">
          <h3>"I shouldn't have gone with their competitor."</h3>
          <p>
            <img src="assets/images/avatar/nan.jpg" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys
          </p>
        </div>
      </div>
    </div>
  </div> -->
</div>
{% endblock content %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

{% block custom_script %}
{% endblock custom_script %}

MacForYou/templates/nav.html
<div class="ui top fixed borderless desktop menu">
  <div class="ui container">
    <a href="/" class="header item nav">
      <img class="logo" src="assets/images/logo.png">
      MacForYou
    </a>
    <!-- <a class="item">ABOUT</a> -->
    <a class="item" href="{% url 'beers:beers_list' %}">TOP20s</a>
    <a class="item" href="{% url 'community:meetups' %}">MeetUPs</a>
    <div class="right menu">
      <div class="item">
        <div class="ui fluid icon input beer search">
          <input placeholder="Search..." type="text" id="beer_search">
          <i class="search link icon nav"></i>
        </div>
      </div>
      {% load socialaccount %}
      {% if user.is_authenticated %}
      <div class="item logout">
        <a class="ui kakao button" href="/accounts/logout/?next={{request.path}} "><i class="comment icon"></i>Logout</a>
        <!-- <a class="ui small blue basic button navlogout">Logout</a> -->
      </div>
        <!-- <a class="ui item navlogout">Logout</a> -->
      {% else %}
      <div class="item login">
        <a class="ui kakao button" href="{% provider_login_url 'kakao' next=request.path %}"><i class="comment icon"></i>LogIn</a>
<!--         <a class="ui kakao button" href="/accounts/kakao/login/?process=login&next=/beers"><i class="comment icon"></i>LogIn</a> -->
      </div>
        <!-- <a class="ui small blue basic button navlogin">Login</a> -->
        <!-- <a class="ui item navlogin">Login</a> -->
      {% endif %}
    </div>
  </div>
</div>