MacForYou/community/urls.py
from django.conf.urls import url
from . import views

app_name = 'community'
urlpatterns = [
	url(r'^$', views.meetup_view, name='meetups'),
	url(r'^(?P<meetup_id>[0-9]+)/$', views.meetup_detail, name='meetup_detail'),
	#url(r'^(?P<party_id>[0-9]+)/results/$', views.results, name='results'),
	url(r'^(?P<party_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'^(?P<meetup_id>[0-9]+)/edit/$', views.meetup_edit, name='meetup_edit'),
	url(r'^create$', views.meetup_create, name='meetup_create'),
	#url(r'^choice_create$', views.choice_create, name='choice_create'),
	url(r'^(?P<pk>\d+)/likes/$', views.party_likes, name='meetup_likes'), 

]

MacForYou/community/models.py
from django.db import models
from django.conf import settings

# def upload_location(party, filename):
#     filebase, extension=filename.split(".")
#     return "%s/%s.%s" %(party.id, filename, extension)

# class Now(models.Model):
#     timenow=datetime.datetime.now()

class Meetup(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title= models.CharField(max_length=30)
    content= models.TextField()
    # preferred_beer= models.CharField(max_length=200)
    # party_beer_image= StdImageField(upload_to=upload_location,
    #  variations={'thumbnail': {'width': 100, 'height': 75}})
    # height_field= models.IntegerField(default=0)
    # width_field= models.IntegerField(default=0)
    place= models.CharField(max_length=200)
    kakao_open_chat_link = models.CharField(max_length=200, blank=True)
    date_meetup= models.DateTimeField()
    mlikes = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

# class Choice(models.Model):
#     party = models.ForeignKey(Party, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)

#     def __str__(self):
#         return self.choice_text

class Mlike(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    party = models.ForeignKey(Meetup, on_delete=models.CASCADE, related_name='meetup_likes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

MacForYou/community/forms.py
from django import forms
from .models import Meetup
from django.forms import DateTimeField


class MeetupModelForm(forms.ModelForm):
    class Meta:
        model = Meetup
        fields = ['title', 'content', 'place', 'kakao_open_chat_link', 'date_meetup' ]

# class ChoiceModelForm(forms.ModelForm):
#     class Meta:
#         model = Choice
#         fields = ['party', 'choice_text',]

MacForYou/community/views.py
from django.shortcuts import redirect, get_object_or_404, render
from .models import Meetup, Mlike
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.template import *
from .forms import MeetupModelForm
from django.views import generic
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import models 
import datetime
# Create your views here.

def meetup_view(request):
	#party_list = Party.objects.order_by('-date_meetup')[:]

	meetup_list = Meetup.objects.filter(date_meetup__gte = datetime.date.today())
	#TO_DO: need to sort out like based order

	context = {'meetup_list': meetup_list}

	return render(request, 'community_cardlist.html', context)


def meetup_detail(request, meetup_id):
	meetup = get_object_or_404(Meetup, pk=meetup_id)
	# return render(request, 'community/party_detail.html', {'meetup': meetup})
	print(meetup)
	return render(request, 'community_detail2.html', {'meetup': meetup})


def vote(request, party_id):
	party = get_object_or_404(Meetup, pk=party_id)
	try:
		selected_choice = party.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form.
		return render(request, 'community/party_detail.html', {
			'party': party,
			'error_message': "You didn't select a choice.",
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
		return HttpResponseRedirect(reverse('community:results', args=(party.id,)))

'''def results(request, party_id):
	party = get_object_or_404(Party, pk=party_id)
	return render(request, 'community/results.html', {'party': party})'''

@login_required
def meetup_create(request):
	form=MeetupModelForm(request.POST or None, request.FILES or None)

	if request.method == 'POST':
		if form.is_valid():
			obj = form.save(commit=False)
			obj.user = request.user
			obj.save()
			return redirect('community:meetups')
	else:
		form=MeetupModelForm()
		content={
			'form':form,
		}	
		# return render(request, 'community/party_form.html', content)
		return render(request, 'community_create.html', content)

'''def choice_create(request):
	form=ChoiceModelForm(request.POST or None)
	if form.is_valid():
		form.save()
		return redirect("/community/")
	else:
		form=ChoiceModelForm()
	content={
		'form':form,
	}
	response = render(request, 'community/choice_form.html', content)
	return response'''

@login_required
def meetup_edit(request, meetup_id):
	
	org_meetup = get_object_or_404(Meetup, pk=meetup_id)
	send_form = MeetupModelForm(instance=org_meetup)

	if request.method == 'POST':
		form = MeetupModelForm(request.POST, request.FILES, instance=org_meetup)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.user = request.user
			obj.save()
			return redirect('community:meetups')
	else:		
		content={
			'form':send_form,
		}	
		# return render(request, 'community/party_form.html', content)
		return render(request, 'community_ce2.html', content)


@login_required # TODO: Ajax로 처리하기
def party_likes(request, pk):
    party = get_object_or_404(Party, pk=pk)
    # 중간자 모델 Like 를 사용하여, 현재 post와 request.user에 해당하는 Like 인스턴스를 가져온다.
    post_likes, post_likes_created = party.likes_set.get_or_create(user=request.user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def home(request):
    return render_to_response('home.html', {}, context_instance=RequestContext(request))

def get_current_path(request):
    return {
       'current_path': request.get_full_path()
     }

MacForYou/community/templates/community/choice_form.html
{% block content %}
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
    <input type="submit" name="submit">
{% endblock %}

MacForYou/community/templates/community/layout.html
{% extends 'layout.html' %}

{% block party %}
    <div class="col-md-2"></div>
    <div class="col-md-8">
        {% block content %}
        {% endblock %}
    </div>
    <div class="col-md-2"></div>
{% endblock %}

MacForYou/community/templates/community/party_detail.html
<h1>{{ meetup.title }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<li>내용: {{ meetup.content }}</li>
	<li>선호하는 맥주: {{ meetup.preferred_beer }}</li>
	<li>모임 장소: {{ meetup.place }}</li>
	<li>만나는 날짜 및 시간: {{ meetup.date_meeting }}</li>
	<li>게시글 올린 날짜: {{meetup.created_at}}</li>
	<li>만나는 날짜: {{meetup.date_meeting}}</li>

<p>참가하려면 눌러주세요</p>



</form>
<a class="badge badge-primary" href="{% url 'community:meetup_likes' meetup.pk %}">{{ meetup.likes_user_set.count }} 참가{{ meetup.likes_user_set.count|pluralize }}</a>
{{meetup.likes_user_set.all}}

<p>{{meetup.party_beer_image}}</p>

<p><img src="{{party.party_beer_image.url}}" class='img-responsive'/> </p>


<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
</head>
<body>
	<script>
		// initialize and setup facebook js sdk
		window.fbAsyncInit = function() {
		    FB.init({
		      appId      : 518406051828571,
		      xfbml      : true,
		      version    : 'v2.5'
		    });
		    FB.getLoginStatus(function(response) {
		    	if (response.status === 'connected') {
		    		document.getElementById('status').innerHTML = 'We are connected.';
		    		document.getElementById('login').style.visibility = 'hidden';
		    	} else if (response.status === 'not_authorized') {
		    		document.getElementById('status').innerHTML = 'We are not logged in.'
		    	} else {
		    		document.getElementById('status').innerHTML = 'You are not logged into Facebook.';
		    	}
		    });
		};
		(function(d, s, id){
		    var js, fjs = d.getElementsByTagName(s)[0];
		    if (d.getElementById(id)) {return;}
		    js = d.createElement(s); js.id = id;
		    js.src = "//connect.facebook.net/en_US/sdk.js";
		    fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
		
		// login with facebook with extra permissions
		function login() {
			FB.login(function(response) {
				if (response.status === 'connected') {
		    		document.getElementById('status').innerHTML = 'We are connected.';
		    		document.getElementById('login').style.visibility = 'hidden';
		    	} else if (response.status === 'not_authorized') {
		    		document.getElementById('status').innerHTML = 'We are not logged in.'
		    	} else {
		    		document.getElementById('status').innerHTML = 'You are not logged into Facebook.';
		    	}
			}, {scope: 'email'});
		}
		
		// getting basic user info
		function getInfo() {
			FB.api('/me', 'GET', {fields: 'first_name,last_name,name,id,picture.width(150).height(150)'}, function(response) {
				document.getElementById('status').innerHTML = "<img src='" + response.picture.data.url + "'>";
			});
		}
	</script>

	<div id="status"></div>
	<button onclick="getInfo()">Get info with picture</button>s
	<button onclick="login()" id="login">Login</button>
</body>
</html>








<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ko_KR/sdk.js#xfbml=1&version=v2.10&appId=145441949376213";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-share-button" data-href="http://www.naver.com" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="http://www.naver.com">공유하기</a></div>


<p>http://localhost:8000/community/{{party.id}}</p>


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ko_KR/sdk.js#xfbml=1&version=v2.10&appId=518406051828571";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<div class="fb-comments" data-href="http://localhost:8000/community/{{party.id}}" data-numposts="5"></div>

MacForYou/community/templates/community/party_form.html
{% block content %}
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
  <input type="datetime-local" name="date_meeting">
    <input type="submit" class="btn btn-default" value="create post">
{% endblock %}

MacForYou/community/templates/community/results.html
<h1>{{ party.title }}</h1>

<ul>
{% for choice in party.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'community:party_detail' party.id %}">Vote again?</a>

MacForYou/community/templates/community_cardlist.html
{% extends "base.html" %}
{% load static %}
{% load socialaccount %}

{% block custom_css_for_page %}
<style type="text/css">

.main.container {
    margin-top: 3em;
}
</style>
{% endblock custom_css_for_page %} 

{% block content %}
<div class="ui main container">
    <div class="ui hidden divider"></div>
    {% if user.is_authenticated %}
    <a class="ui labeled icon right floated primary basic button" href="{% url 'community:meetup_create' %}"><i class="add square icon"></i>make meetup</a>
    {% else %}
    <a class="ui labeled icon right floated primary basic button" href="{% provider_login_url 'kakao' next=request.path %}"><i class="add square icon"></i>login to make meetup</a>
    {% endif %}
    <h3 class="ui dividing header">Meetup: List</h3>
    <div class="ui three stackable cards">
        {% for meetup in meetup_list %}
        <div class="ui card">
            <div class="content">
                <div class="right floated meta">{{ meetup.created|timesince }}</div>
                <img class="ui avatar image" src="/images/avatar/large/elliot.jpg"> Elliot
<!--                 <div class="header">{{ meetup.title }}</div>
                <div class="meta">
                    <span class="right floated time">{{ meetup.created|timesince }}</span>                    
                </div> -->
            </div>
            <div class="content">
                <div class="header">{{ meetup.title }}</div>
                <div class="description" style="word-break: break-all; text-overflow: ellipsis;">
                    {{ meetup.content|truncatewords:10 }}
                </div>
            </div>
            <div class="extra content">
<!--                 <div class="right floated author">
                    <img class="ui avatar image" src="/images/avatar/small/matt.jpg"> {{ meetup.user.nickname}}
                </div> -->
                <span><i class="heart outline like icon"></i>{{meetup.mlikes}} likes</span>
<!--                 <div class="ui one button right floated">
                    <div class="tiny ui basic green button">Learn More</div>
                </div> -->
                <a class="small ui basic green button right floated" href="{% url 'community:meetup_detail' meetup.id %}">Learn More</a>
<!--                 <div class="right floated author">
                    <span><i class="heart outline like icon"></i>35 likes</span>
                </div> -->
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

{% block footer %}
    {% include "footer.html" %}
{% endblock %}

{% block custom_script %}

{% endblock custom_script %}

MacForYou/community/templates/community_ce2.html
{% extends "base.html" %}
{% load static %}

{% block custom_css_for_page %}
<!-- <script type="text/javascript" src="/bower_components/semantic-ui-calendar/dist/calendar.min.js"></script> -->

<!-- <link rel="stylesheet" href="/bower_components/semantic-ui-calendar/dist/calendar.min.css" /> -->
<link rel="stylesheet" href="{% static 'calendar.min.css' %}" />
<style type="text/css">
	body {
	  background-color: #E2ED99;
	}
	body > .grid {
	  height: 100%;
	}
	.image {
	  margin-top: -100px;
	}
	.column {
	  max-width: 450px;
	}
</style>
{% endblock custom_css_for_page %}

{% block content %}
<div class="ui middle aligned center aligned grid">
    <div class="column">
        <h2 class="ui icon header">
            <i class="users icon"></i>
            <div class="content">Create Meetup</div>
            <div class="sub header">Create your own meetup</div>
        </h2>
        
        <form class="ui large form" id="meetup_create_form" action="{% url 'community:meetup_create' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="ui stacked segment">            
                <div class="required field">
                    {{form.title.errors}}
                    <div class="ui left icon input">
                        <!-- <label for="{{form.title.id_for_label}}">Title</label> -->
                        <i class="write icon"></i>
                        <input name="{{ form.title.html_name }}" id="{{form.title.id_for_label}}" placeholder="meetup title">{{form.title.value|default_if_none:''}}</input>
                    </div>
                </div>
                <div class="required field">
                    {{form.date_meetup.errors}}
                     <div class="ui calendar" id="meetup_datetime">

                        <!-- <label for="{{form.date_meetup.id_for_label}}">DATE</label> -->
                        <div class="ui left icon input">
                            <i class="calendar icon"></i>                     
                            <input type="text" name="{{ form.date_meetup.html_name }}" id="{{form.date_meetup.id_for_label}}" placeholder="date time of meetup">{{form.date_meetup.value|default_if_none:''}}</input>
                        </div>
                    </div>
                </div>
                <div class="required field">
                    {{form.content.errors}}
                    <div class="ui left icon input">
                        <!-- <label for="{{form.content.id_for_label}}">Content</label> -->
                        
                        <textarea name="{{ form.content.html_name }}" rows="3" id="{{form.content.id_for_label}}" placeholder="detail of meetup">{{form.content.value|default_if_none:''}}</textarea>
                    </div>
                </div>
                <div class="required field">
                    {{form.place.errors}}
                    <div class="ui left icon input">
                        <!-- <label for="{{form.place.id_for_label}}">Place</label> -->
                        <i class="map outline icon"></i>
                        <input name="{{ form.place.html_name }}" id="{{form.place.id_for_label}}" placeholder="place">{{form.place.value|default_if_none:''}}</input>
                    </div>
                </div>
                <div class="field">
                    {{form.kakao_open_chat_link.errors}}
                    <div class="ui left icon input">
                        <!-- <label for="{{form.kakao_open_chat_link.id_for_label}}">KAKAO OpenChat</label> -->
                        <i class="comments outline icon"></i>
                        <input name="{{ form.kakao_open_chat_link.html_name }}" id="{{form.kakao_open_chat_link.id_for_label}}" placeholder="KAKAO OpenChat Link">{{form.kakao_open_chat_link.value|default_if_none:''}}</input>
                    </div>
                </div>
                <div class="ui large red cancel inverted button" id="create_meetup_cancel_btn">Cancel</div>
                <div class="ui large green submit inverted button" id="create_meetup_submit_btn">Submit</div>                
            </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block custom_script %}
<script type="text/javascript" src="{% static 'calendar.min.js' %}"></script>
<script type="text/javascript">
	// $('.tiny.modal.create_review').modal('show');
    // $('#meetup_datetime').calendar();
    $("#create_meetup_submit_btn").click(function() {
        $("#meetup_create_form").submit();
    });
    $("#create_meetup_cancel_btn").click(function() {
        window.location.href = '{% url 'community:meetups' %}';
    });

</script>
{% endblock custom_script %}

MacForYou/community/templates/community_create.html
{% extends "base.html" %}
{% load static %}

{% block custom_css_for_page %}
<!-- <script type="text/javascript" src="/bower_components/semantic-ui-calendar/dist/calendar.min.js"></script> -->

<!-- <link rel="stylesheet" href="/bower_components/semantic-ui-calendar/dist/calendar.min.css" /> -->
<!-- <link rel="stylesheet" href="{% static 'calendar.min.css' %}" /> -->
<style type="text/css">
	body {
	  background-color: #E2ED99;
	}
	body > .grid {
	  height: 100%;
	}
	.image {
	  margin-top: -100px;
	}
	.column {
	  max-width: 450px;
	}
</style>
{% endblock custom_css_for_page %}

{% block content %}
<div class="ui middle aligned center aligned grid">
    <div class="column">
        <h2 class="ui icon header">
            <i class="users icon"></i>
            <div class="content">Create Meetup</div>
            <div class="sub header">Create your own meetup</div>
        </h2>
        
        <form class="ui large form" id="meetup_create_form" action="{% url 'community:meetup_create' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="ui stacked segment">            
                <div class="required field">
                    {{form.title.errors}}
                    <div class="ui left icon input">
                        <!-- <label for="{{form.title.id_for_label}}">Title</label> -->
                        <i class="write icon"></i>
                        <input name="{{ form.title.html_name }}" id="{{form.title.id_for_label}}" placeholder="meetup title">{{form.title.value|default_if_none:''}}</input>
                    </div>
                </div>
                <div class="required field">
                    {{form.date_meetup.errors}}
                     <div class="ui calendar" id="meetup_datetime">

                        <!-- <label for="{{form.date_meetup.id_for_label}}">DATE</label> -->
                        <div class="ui left icon input">
                            <i class="calendar icon"></i>                     
                            <input type="date" name="{{ form.date_meetup.html_name }}" id="{{form.date_meetup.id_for_label}}" placeholder="date time of meetup">{{form.date_meetup.value|default_if_none:''}}</input>
                        </div>
                    </div>
                </div>
                <div class="required field">
                    {{form.content.errors}}
                    <div class="ui left icon input">
                        <!-- <label for="{{form.content.id_for_label}}">Content</label> -->
                        
                        <textarea name="{{ form.content.html_name }}" rows="3" id="{{form.content.id_for_label}}" placeholder="detail of meetup">{{form.content.value|default_if_none:''}}</textarea>
                    </div>
                </div>
                <div class="required field">
                    {{form.place.errors}}
                    <div class="ui left icon input">
                        <!-- <label for="{{form.place.id_for_label}}">Place</label> -->
                        <i class="map outline icon"></i>
                        <input name="{{ form.place.html_name }}" id="{{form.place.id_for_label}}" placeholder="place">{{form.place.value|default_if_none:''}}</input>
                    </div>
                </div>
                <div class="field">
                    {{form.kakao_open_chat_link.errors}}
                    <div class="ui left icon input">
                        <!-- <label for="{{form.kakao_open_chat_link.id_for_label}}">KAKAO OpenChat</label> -->
                        <i class="comments outline icon"></i>
                        <input name="{{ form.kakao_open_chat_link.html_name }}" id="{{form.kakao_open_chat_link.id_for_label}}" placeholder="KAKAO OpenChat Link">{{form.kakao_open_chat_link.value|default_if_none:''}}</input>
                    </div>
                </div>
                <div class="ui large red cancel inverted button" id="create_meetup_cancel_btn">Cancel</div>
                <div class="ui large green submit inverted button" id="create_meetup_submit_btn">Submit</div>                
            </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block custom_script %}
<!-- <script type="text/javascript" src="{% static 'calendar.min.js' %}"></script> -->
<script type="text/javascript">
	// $('.tiny.modal.create_review').modal('show');
    // $('#meetup_datetime').calendar();
    $("#create_meetup_submit_btn").click(function() {
        $("#meetup_create_form").submit();
    });
    $("#create_meetup_cancel_btn").click(function() {
        window.location.href = '{% url 'community:meetups' %}';
    });

</script>
{% endblock custom_script %}

MacForYou/community/templates/community_detail2.html
{% extends "base.html" %}
{% load static %}

{% block custom_css_for_page %}
<style type="text/css">
	body {
	  background-color: #E2ED99;
	}
	body > .grid {
	  height: 100%;
	}
	.image {
	  margin-top: -100px;
	}
	.column {
	  max-width: 450px;
	}
</style>
{% endblock custom_css_for_page %}

{% block content %}
<div class="ui middle aligned center aligned grid">
	<div class="column">
     	<h2 class="ui icon header">
     		<i class="users icon"></i>
         		<div class="content">Meetup</div>
         		<div class="sub header">{{meetup.title}}</div>
         	</h2>

		<div class="content">
			<p>Lets meet at {{meetup.place}} </p>
			<p>at {{meetup.date_meetup}}</p>
			<p>{{meetup.content|linebreaks}}</p>
			<p>join us at {{meetup.kakao_open_chat_link}}</p>

			<div class="ui large red cancel inverted button" id="create_meetup_cancel_btn">Cancel</div>
		</div>
    	</div>
        
        <!-- <form class="ui large form" id="meetup_create_form" action="{% url 'community:meetup_create' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="ui stacked segment">            
                <div class="required field">
                    {{form.title.errors}}
                    <div class="ui left icon input">
                        <i class="write icon"></i>
                        <input name="{{ form.title.html_name }}" id="{{form.title.id_for_label}}" placeholder="meetup title">{{form.title.value|default_if_none:''}}</input>
                    </div>
                </div>
                <div class="required field">
                    {{form.date_meetup.errors}}
                     <div class="ui calendar" id="meetup_datetime">
                        <div class="ui left icon input">
                            <i class="calendar icon"></i>                     
                            <input type="text" name="{{ form.date_meetup.html_name }}" id="{{form.date_meetup.id_for_label}}" placeholder="date time of meetup">{{form.date_meetup.value|default_if_none:''}}</input>
                        </div>
                    </div>
                </div>
                <div class="required field">
                    {{form.content.errors}}
                    <div class="ui left icon input">
                        <textarea name="{{ form.content.html_name }}" rows="3" id="{{form.content.id_for_label}}" placeholder="detail of meetup">{{form.content.value|default_if_none:''}}</textarea>
                    </div>
                </div>
                <div class="required field">
                    {{form.place.errors}}
                    <div class="ui left icon input">
                        <i class="map outline icon"></i>
                        <input name="{{ form.place.html_name }}" id="{{form.place.id_for_label}}" placeholder="place">{{form.place.value|default_if_none:''}}</input>
                    </div>
                </div>
                <div class="field">
                    {{form.kakao_open_chat_link.errors}}
                    <div class="ui left icon input">
                        <i class="comments outline icon"></i>
                        <input name="{{ form.kakao_open_chat_link.html_name }}" id="{{form.kakao_open_chat_link.id_for_label}}" placeholder="KAKAO OpenChat Link">{{form.kakao_open_chat_link.value|default_if_none:''}}</input>
                    </div>
                </div>
                <div class="ui large red cancel inverted button" id="create_meetup_cancel_btn">Cancel</div>
                <div class="ui large green submit inverted button" id="create_meetup_submit_btn">Submit</div>                
            </div>
        </form> -->
    </div>
</div>
{% endblock content %}

{% block custom_script %}
<script type="text/javascript">

</script>
{% endblock custom_script %}

MacForYou/community/templates/community_list.html
{% extends "base.html" %} 
{% load static %} 
{% block custom_css_for_page %}
<style type="text/css">
body {
    background-color: #FFFFFF;
}

.ui.menu .item img.logo {
    margin-right: 1.5em;
}

.main.container {
    margin-top: 5em;
}
</style>
{% endblock custom_css_for_page %} 

{% block content %}
<div class="ui main container">
    <div class="ui hidden divider"></div>
    <h3 class="ui dividing header">Community: List</h3>
    <div class="ui large middle aligned divided list">
      {% for meetup in meetup_list %}
      <div class="item">
        <div class="right floated content">
          <!-- <div class="ui star rating review result " data-rating="3 " data-max-rating="5 "></div> -->
          <p style="text-align: right;">현재 참가 인원: {{ meetup.likes_user_set.count }}</p>
        </div>
        <!-- <img class="ui avatar image " src="/images/avatar/small/daniel.jpg "> -->
        <div class="content">
          <a class="header" href="{% url 'community:meetup_detail' meetup.id %}"> {{ meetup.title }} </a>
          <p> {{ meetup.content }} </p>
        </div>
      </div>
      {% endfor %}
    </div>
</div>
{% endblock content %}

{% block custom_script %}

{% endblock custom_script %}